# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: 🌐 Package 📦 + 🚀 Deploy 🌐

# Builds packages for every device and architecture libhal supports

on:
  workflow_call:
    inputs:
      library:
        type: string
        default: ${{ github.event.repository.name }}
      repo:
        type: string
        default: ${{ github.repository }}
      version:
        type: string
        default: ""
      conan_version:
        type: string
        default: "2.0.14"

jobs:
  cortex-m0:
    uses: ./.github/workflows/deploy.yml
    with:
      library: ${{ inputs.library }}
      repo: ${{ inputs.repo }}
      version: ${{ inputs.version }}
      conan_version: ${{ inputs.conan_version }}
      compiler: gcc
      compiler_version: 12.3
      compiler_package: arm-gnu-toolchain
      arch: cortex-m0
      os: baremetal
    secrets: inherit
  cortex-m0plus:
    uses: ./.github/workflows/deploy.yml
    with:
      library: ${{ inputs.library }}
      repo: ${{ inputs.repo }}
      version: ${{ inputs.version }}
      conan_version: ${{ inputs.conan_version }}
      compiler: gcc
      compiler_version: 12.3
      compiler_package: arm-gnu-toolchain
      arch: cortex-m0plus
      os: baremetal
    secrets: inherit
  cortex-m1:
    uses: ./.github/workflows/deploy.yml
    with:
      library: ${{ inputs.library }}
      repo: ${{ inputs.repo }}
      version: ${{ inputs.version }}
      conan_version: ${{ inputs.conan_version }}
      compiler: gcc
      compiler_version: 12.3
      compiler_package: arm-gnu-toolchain
      arch: cortex-m1
      os: baremetal
    secrets: inherit
  cortex-m3:
    uses: ./.github/workflows/deploy.yml
    with:
      library: ${{ inputs.library }}
      repo: ${{ inputs.repo }}
      version: ${{ inputs.version }}
      conan_version: ${{ inputs.conan_version }}
      compiler: gcc
      compiler_version: 12.3
      compiler_package: arm-gnu-toolchain
      arch: cortex-m3
      os: baremetal
    secrets: inherit
  cortex-m4:
    uses: ./.github/workflows/deploy.yml
    with:
      library: ${{ inputs.library }}
      repo: ${{ inputs.repo }}
      version: ${{ inputs.version }}
      conan_version: ${{ inputs.conan_version }}
      compiler: gcc
      compiler_version: 12.3
      compiler_package: arm-gnu-toolchain
      arch: cortex-m4
      os: baremetal
    secrets: inherit
  cortex-m4f:
    uses: ./.github/workflows/deploy.yml
    with:
      library: ${{ inputs.library }}
      repo: ${{ inputs.repo }}
      version: ${{ inputs.version }}
      conan_version: ${{ inputs.conan_version }}
      compiler: gcc
      compiler_version: 12.3
      compiler_package: arm-gnu-toolchain
      arch: cortex-m4f
      os: baremetal
    secrets: inherit
